"""
Abstract Base Class for Trading Strategies.
All custom strategies must implement this interface to be compatible with BacktestEngine.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import List, Dict, Any
import pandas as pd


@dataclass
class TradeSignal:
    """Represents a single trade signal generated by a strategy."""
    date: str
    price: float
    action: str  # 'BUY' or 'SELL'
    reason: str
    score: float = 0.0


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    To create a new strategy:
    1. Subclass BaseStrategy
    2. Implement `name`, `initialize()`, and `generate_signals()`
    3. Register in `src/analysis/strategies/__init__.py`
    """
    
    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable strategy name for UI display."""
        pass
    
    @abstractmethod
    def initialize(self, params: Dict[str, Any]) -> None:
        """
        Initialize strategy with custom parameters.
        
        Args:
            params: Strategy-specific configuration dictionary.
                    Common keys may include 'threshold_value', 'lookback_period', etc.
        """
        pass
    
    @abstractmethod
    def generate_signals(self, data: pd.DataFrame, start_date: str, end_date: str) -> List[TradeSignal]:
        """
        Generate buy/sell signals for the given data range.
        
        Args:
            data: OHLCV DataFrame with columns: 'date', 'open', 'high', 'low', 'close', 'volume'
            start_date: Signal generation start date (YYYY-MM-DD)
            end_date: Signal generation end date (YYYY-MM-DD)
            
        Returns:
            List of TradeSignal objects representing when to buy/sell.
        """
        pass
    
    def optimize_params(self, data: pd.DataFrame) -> Dict[str, Any]:
        """
        Optional: Auto-optimize strategy parameters using historical data.
        
        Args:
            data: Historical OHLCV data for optimization.
            
        Returns:
            Optimized parameter dictionary.
        """
        return {}  # Default: no optimization
